version: '3.8'

services:
  web:
    build: .
    container_name: sqli-labs-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    image: sqli-labs-web:1.1

  db:
    image: mysql:5.7
    container_name: sqli-labs-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: security
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
   
volumes:
  db-data:

